FROM ubuntu:latest
MAINTAINER Kai-Siyuan <siyuanliu@ucsd.edu>

# Add scripts into the image
COPY host_data/server/PingPongServer.class data/server/
COPY host_data/client/PingPongClient.class data/client/
COPY host_data/common/PingPongInterface.class data/common/
COPY host_data/server/PingServerFactory.class data/server/
COPY host_data/rmi.jar data/
