FROM ubuntu:latest
MAINTAINER Kai-Siyuan <siyuanliu@ucsd.edu>

# Add scripts into the image
COPY host_data/PingPongClient.class data/
COPY host_data/PingPongServer.class data/
COPY host_data/rmi.jar data/
